name: Auto Build, Publish, Releasing

on:
  workflow_dispatch:
    inputs:
      publishMaven:
        description: 'whether to publish to the maven'
        required: true
        type: boolean
        default: true
      publishCurseForgeAndModrinth:
        description: 'whether to publish to curseforge and modrinth'
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - if: ${{ inputs.publishMaven }}
        name: Publish to Maven
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publish

      - if: ${{ inputs.publishCurseForgeAndModrinth }}
        name: Get Version
        id: var
        run: |
          MESSAGE=$(ls build/libs/* | grep sources.jar -v | grep shadow.jar -v | awk -F 'ldlib-neoforge-|.jar' '{print $2}')
          echo version=$MESSAGE >> $GITHUB_OUTPUT

      - if: ${{ inputs.publishCurseForgeAndModrinth }}
        name: mc-publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: B1CBVXHX
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 626676
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc|dev-shadow)).jar
            build/libs/*-@(dev|sources|javadoc|dev-shadow).jar

          name: LDLib ${{ steps.var.outputs.version }}-neoforge
          version: mc${{ steps.var.outputs.version }}-neoforge
          version-type: release
          changelog-file: CHANGELOG.*

          loaders: |
            neoforge
          game-versions: |
            ${{ github.ref_name }}
          game-version-filter: none
          java: |
            21
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
